apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  selector:
    matchLabels:
      app: demo-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
        - name: demo-backend
          image: luatnq/backend-demo-service:46f4744
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: demo-backend-cm
            - secretRef:
                name: demo-backend-sc
          ports:
            - containerPort: 8081
              name: http
      restartPolicy: Always
