apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  selector:
      matchLabels:
        app: demo-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
        - name: demo-backend
          image: luatnq/spring-cache_demo-cache:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
