kind: Service
apiVersion: v1
metadata:
  name: demo-backend
spec:
  selector:
    app: demo-backend
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8081
      nodePort: 30123
  type: LoadBalancer
