kind: Service
apiVersion: v1
metadata:
  name: demo-backend
spec:
  selector:
    app: demo-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Local
